import React, { useState } from 'react';
import confetti from 'canvas-confetti';
import { 
  Sparkles, BrainCircuit, AlertTriangle, TrendingDown, 
  Lightbulb, ShieldCheck, Download, Copy, Check, ChevronRight 
} from 'lucide-react';

export default function AIInsights({ onGenerate, insights = null, loading = false, error = '' }) {
  const [copied, setCopied] = useState(false);

  const handleGenerateClick = async () => {
    await onGenerate();
    confetti({
      particleCount: 50,
      spread: 60,
      origin: { y: 0.6 }
    });
  };

  const handleCopyReport = () => {
    if (!insights) return;
    const text = `
=== SMART EXPENSE TRACKER AI REPORT ===
Generated by: ${insights.generatedBy || 'AI Engine'}
Health Score: ${insights.healthScore}/100
Total Spent: $${insights.totalSpent?.toFixed(2)}

SUMMARY:
${insights.summary}

PATTERNS DETECTED:
${insights.patterns?.map(p => `- [${p.impact || 'Info'}] ${p.title}: ${p.description}`).join('\n')}

ANOMALIES & SPIKES:
${insights.anomalies?.map(a => `- ${a.title}: ${a.description}`).join('\n')}

ACTIONABLE SUGGESTIONS:
${insights.suggestions?.map(s => `- ${s.title}: ${s.description} (Savings: ${s.potentialSavings || 'N/A'})`).join('\n')}
`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="glass-card animate-fade-in" style={{
      padding: '28px',
      marginBottom: '24px',
      background: 'linear-gradient(145deg, rgba(15, 23, 42, 0.9), rgba(30, 27, 75, 0.6))',
      border: '1px solid rgba(139, 92, 246, 0.3)',
      position: 'relative',
      overflow: 'hidden'
    }}>
      {/* Decorative background glow */}
      <div style={{
        position: 'absolute',
        top: '-40px',
        right: '-40px',
        width: '180px',
        height: '180px',
        background: 'radial-gradient(circle, rgba(139, 92, 246, 0.25) 0%, transparent 70%)',
        pointerEvents: 'none'
      }} />

      {/* Header */}
      <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: '16px', marginBottom: '20px' }}>
        <div>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            <div style={{
              padding: '8px',
              borderRadius: '10px',
              background: 'linear-gradient(135deg, #8B5CF6, #EC4899)',
              color: '#fff',
              display: 'flex'
            }}>
              <BrainCircuit size={22} />
            </div>
            <div>
              <h2 style={{ fontFamily: 'var(--font-heading)', fontSize: '1.3rem', color: '#ffffff' }}>
                AI Expense Pattern & Insight Engine
              </h2>
              <p style={{ fontSize: '0.82rem', color: 'var(--text-secondary)' }}>
                Powered by Gemini & OpenAI deep pattern analysis
              </p>
            </div>
          </div>
        </div>

        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          {insights && (
            <button 
              onClick={handleCopyReport} 
              className="glow-btn glow-btn-secondary"
              title="Copy formatted markdown report"
            >
              {copied ? <Check size={15} color="#10B981" /> : <Copy size={15} />}
              {copied ? 'Copied!' : 'Copy Report'}
            </button>
          )}

          <button 
            onClick={handleGenerateClick}
            disabled={loading}
            className="glow-btn"
            style={{ background: 'linear-gradient(135deg, #8B5CF6, #6366F1)' }}
          >
            <Sparkles size={16} className={loading ? 'pulse-glow' : ''} />
            {loading ? 'Analyzing Entries...' : (insights ? 'Re-Generate Insights' : 'Analyze Expenses with AI')}
          </button>
        </div>
      </div>

      {error && (
        <div style={{
          background: 'rgba(244, 63, 94, 0.15)',
          border: '1px solid rgba(244, 63, 94, 0.4)',
          color: '#fda4af',
          padding: '12px 16px',
          borderRadius: '10px',
          fontSize: '0.85rem',
          marginBottom: '20px'
        }}>
          {error}
        </div>
      )}

      {/* Initial state if no report generated yet */}
      {!insights && !loading && (
        <div style={{
          background: 'rgba(15, 23, 42, 0.5)',
          border: '1px dashed rgba(255, 255, 255, 0.12)',
          borderRadius: '14px',
          padding: '32px',
          textAlign: 'center'
        }}>
          <BrainCircuit size={42} color="#8B5CF6" style={{ marginBottom: '12px', opacity: 0.8 }} />
          <h3 style={{ color: '#ffffff', fontSize: '1.05rem', marginBottom: '6px' }}>
            Ready to unlock spending insights?
          </h3>
          <p style={{ color: 'var(--text-secondary)', fontSize: '0.88rem', maxWidth: '500px', margin: '0 auto 16px auto' }}>
            Click the button above to aggregate all logged expense entries and send them to the AI engine. You'll receive category breakdown analysis, anomaly alerts, and tailored savings tips.
          </p>
        </div>
      )}

      {/* Loading state skeleton */}
      {loading && (
        <div style={{ padding: '30px', textAlign: 'center' }}>
          <div className="pulse-glow" style={{ fontSize: '1rem', color: '#a5b4fc', marginBottom: '8px', fontWeight: 600 }}>
            🧠 Aggregating transaction logs & contacting AI engine...
          </div>
          <p style={{ fontSize: '0.8rem', color: 'var(--text-muted)' }}>
            Examining recurring charges, category weights, and savings opportunities
          </p>
        </div>
      )}

      {/* Report display */}
      {insights && !loading && (
        <div className="animate-fade-in" style={{ display: 'flex', flexDirection: 'column', gap: '20px' }}>
          {/* Executive Summary Card */}
          <div style={{
            background: 'rgba(255, 255, 255, 0.04)',
            border: '1px solid rgba(255, 255, 255, 0.08)',
            padding: '20px',
            borderRadius: '14px',
            display: 'flex',
            alignItems: 'flex-start',
            gap: '16px',
            flexWrap: 'wrap'
          }}>
            <div style={{ flex: 1, minWidth: '260px' }}>
              <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
                <span className="badge badge-indigo">
                  Generated by {insights.generatedBy}
                </span>
              </div>
              <p style={{ fontSize: '0.95rem', color: '#e2e8f0', lineHeight: 1.5 }}>
                {insights.summary}
              </p>
            </div>

            {insights.healthScore !== undefined && (
              <div style={{
                background: 'rgba(15, 23, 42, 0.8)',
                border: '1px solid rgba(255, 255, 255, 0.12)',
                borderRadius: '12px',
                padding: '14px 20px',
                textAlign: 'center',
                minWidth: '130px'
              }}>
                <div style={{ fontSize: '0.75rem', color: 'var(--text-muted)', textTransform: 'uppercase', fontWeight: 600 }}>
                  Financial Health
                </div>
                <div style={{
                  fontSize: '1.8rem',
                  fontWeight: 800,
                  fontFamily: 'var(--font-heading)',
                  color: insights.healthScore >= 75 ? '#10B981' : insights.healthScore >= 50 ? '#F59E0B' : '#F43F5E'
                }}>
                  {insights.healthScore}
                  <span style={{ fontSize: '0.9rem', color: 'var(--text-muted)' }}>/100</span>
                </div>
              </div>
            )}
          </div>

          {/* Grid of Patterns, Anomalies, and Suggestions */}
          <div style={{
            display: 'grid',
            gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))',
            gap: '18px'
          }}>
            {/* Patterns */}
            <div style={{
              background: 'rgba(15, 23, 42, 0.6)',
              border: '1px solid rgba(99, 102, 241, 0.2)',
              borderRadius: '14px',
              padding: '18px'
            }}>
              <h3 style={{ fontSize: '0.95rem', fontWeight: 700, color: '#a5b4fc', display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '14px' }}>
                <TrendingDown size={16} />
                Observed Spending Patterns
              </h3>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                {insights.patterns?.map((item, idx) => (
                  <div key={idx} style={{ background: 'rgba(255,255,255,0.03)', padding: '12px', borderRadius: '8px', borderLeft: '3px solid #6366F1' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '4px' }}>
                      <span style={{ fontSize: '0.85rem', fontWeight: 600, color: '#ffffff' }}>{item.title}</span>
                      <span className={`badge ${item.impact === 'High' ? 'badge-rose' : item.impact === 'Medium' ? 'badge-amber' : 'badge-indigo'}`}>
                        {item.impact || 'Pattern'}
                      </span>
                    </div>
                    <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>{item.description}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Anomalies & Spikes */}
            <div style={{
              background: 'rgba(15, 23, 42, 0.6)',
              border: '1px solid rgba(244, 63, 94, 0.2)',
              borderRadius: '14px',
              padding: '18px'
            }}>
              <h3 style={{ fontSize: '0.95rem', fontWeight: 700, color: '#fda4af', display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '14px' }}>
                <AlertTriangle size={16} />
                Anomalies & High Outliers
              </h3>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                {insights.anomalies?.map((item, idx) => (
                  <div key={idx} style={{ background: 'rgba(255,255,255,0.03)', padding: '12px', borderRadius: '8px', borderLeft: '3px solid #F43F5E' }}>
                    <div style={{ fontSize: '0.85rem', fontWeight: 600, color: '#ffffff', marginBottom: '4px' }}>
                      {item.title}
                    </div>
                    <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>{item.description}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Suggestions & Savings Tips */}
            <div style={{
              background: 'rgba(15, 23, 42, 0.6)',
              border: '1px solid rgba(16, 185, 129, 0.2)',
              borderRadius: '14px',
              padding: '18px'
            }}>
              <h3 style={{ fontSize: '0.95rem', fontWeight: 700, color: '#6ee7b7', display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '14px' }}>
                <Lightbulb size={16} />
                Actionable Savings Opportunities
              </h3>
              <div style={{ display: 'flex', flexDirection: 'column', gap: '10px' }}>
                {insights.suggestions?.map((item, idx) => (
                  <div key={idx} style={{ background: 'rgba(255,255,255,0.03)', padding: '12px', borderRadius: '8px', borderLeft: '3px solid #10B981' }}>
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '4px' }}>
                      <span style={{ fontSize: '0.85rem', fontWeight: 600, color: '#ffffff' }}>{item.title}</span>
                      {item.potentialSavings && (
                        <span className="badge badge-emerald">
                          {item.potentialSavings}
                        </span>
                      )}
                    </div>
                    <p style={{ fontSize: '0.8rem', color: 'var(--text-secondary)' }}>{item.description}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
