import React, { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import confetti from 'canvas-confetti';
import { 
  Sparkles, BrainCircuit, AlertTriangle, TrendingDown, 
  Lightbulb, ShieldCheck, Copy, Check, MessageSquare, Bot, ArrowRight, Zap 
} from 'lucide-react';
import Card from './ui/Card';
import Button from './ui/Button';
import Badge from './ui/Badge';

export default function AIInsights({ onGenerate, insights = null, loading = false, error = '' }) {
  const [copied, setCopied] = useState(false);
  const [activePrompt, setActivePrompt] = useState(null);

  const samplePrompts = [
    '💸 How much did I spend this month?',
    '📊 Where am I overspending?',
    '🍕 Compare food vs transportation outlay',
    '🐖 Am I saving enough for my targets?'
  ];

  const handleGenerateClick = async (promptText) => {
    if (promptText) setActivePrompt(promptText);
    await onGenerate();
    confetti({
      particleCount: 50,
      spread: 60,
      origin: { y: 0.6 }
    });
  };

  const handleCopyReport = () => {
    if (!insights) return;
    const text = `
=== SMART EXPENSE TRACKER AI REPORT ===
Generated by: ${insights.generatedBy || 'AI Engine'}
Health Score: ${insights.healthScore}/100
Total Spent: $${insights.totalSpent?.toFixed(2)}

SUMMARY:
${insights.summary}

PATTERNS DETECTED:
${insights.patterns?.map(p => `- [${p.impact || 'Info'}] ${p.title}: ${p.description}`).join('\n')}

ANOMALIES & SPIKES:
${insights.anomalies?.map(a => `- ${a.title}: ${a.description}`).join('\n')}

ACTIONABLE SUGGESTIONS:
${insights.suggestions?.map(s => `- ${s.title}: ${s.description} (Savings: ${s.potentialSavings || 'N/A'})`).join('\n')}
`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <Card padding="p-8" className="mb-8 relative overflow-hidden bg-gradient-to-br from-slate-950 via-purple-950/40 to-slate-950 border-purple-500/30 shadow-2xl">
      
      {/* Decorative Glow Orb Background */}
      <div className="absolute top-0 right-0 w-80 h-80 bg-purple-600/15 blur-[100px] rounded-full pointer-events-none -z-10" />

      {/* CENTERPIECE HEADER */}
      <div className="flex flex-col lg:flex-row lg:items-center justify-between gap-4 mb-6 pb-6 border-b border-slate-800/80">
        <div className="flex items-center gap-3">
          <div className="p-3 rounded-2xl bg-gradient-to-br from-purple-600 to-pink-600 text-white shadow-lg shadow-purple-500/30">
            <BrainCircuit className="w-6 h-6" />
          </div>
          <div>
            <div className="flex items-center gap-2">
              <h2 className="text-xl md:text-2xl font-extrabold text-white tracking-tight">
                AI Finance Assistant & Pattern Engine
              </h2>
              <Badge variant="purple" size="sm">
                <Sparkles className="w-3 h-3 text-purple-400" /> Gemini 2.5 + Llama-3
              </Badge>
            </div>
            <p className="text-xs text-slate-400 mt-0.5">
              Deep transaction categorization, cashflow anomaly detection, and automated savings recommendations
            </p>
          </div>
        </div>

        <div className="flex items-center gap-3">
          {insights && (
            <Button
              size="sm"
              variant="secondary"
              onClick={handleCopyReport}
              icon={copied ? Check : Copy}
            >
              {copied ? 'Copied Markdown' : 'Copy Report'}
            </Button>
          )}

          <Button
            size="md"
            variant="primary"
            onClick={() => handleGenerateClick(null)}
            isLoading={loading}
            icon={Sparkles}
          >
            {loading ? 'Analyzing Transactions...' : (insights ? 'Re-Generate Report' : 'Analyze Expenses with AI')}
          </Button>
        </div>
      </div>

      {/* SAMPLE PROMPT QUICK LAUNCH PILLS */}
      <div className="mb-6 bg-slate-900/80 p-4 rounded-2xl border border-slate-800 space-y-2">
        <span className="text-[11px] font-semibold text-purple-400 uppercase tracking-widest flex items-center gap-1.5">
          <MessageSquare className="w-3.5 h-3.5" /> Interactive Quick Prompts
        </span>
        <div className="flex flex-wrap gap-2 text-xs">
          {samplePrompts.map((prompt, idx) => (
            <button
              key={idx}
              onClick={() => handleGenerateClick(prompt)}
              disabled={loading}
              className="bg-slate-800/80 hover:bg-purple-900/40 text-slate-300 hover:text-purple-200 px-3 py-1.5 rounded-xl border border-slate-700/60 hover:border-purple-500/40 font-medium transition-all cursor-pointer text-xs"
            >
              {prompt}
            </button>
          ))}
        </div>
      </div>

      {error && (
        <div className="bg-rose-500/10 border border-rose-500/30 p-4 rounded-2xl text-xs text-rose-300 mb-6">
          {error}
        </div>
      )}

      {/* INITIAL EMPTY STATE */}
      {!insights && !loading && (
        <div className="bg-slate-900/40 border border-dashed border-slate-800 rounded-2xl p-8 text-center space-y-3">
          <Bot className="w-12 h-12 text-purple-400 mx-auto opacity-70" />
          <h3 className="text-base font-bold text-white">Ready to unlock spending insights?</h3>
          <p className="text-xs text-slate-400 max-w-md mx-auto leading-relaxed">
            Click any prompt above or click <strong>Analyze Expenses with AI</strong> to generate financial health scores, detect outlay spikes, and uncover monthly savings opportunities.
          </p>
        </div>
      )}

      {/* LOADING PULSE STATE */}
      {loading && (
        <div className="py-12 text-center space-y-3">
          <div className="animate-pulse-glow text-sm text-purple-300 font-bold flex items-center justify-center gap-2">
            <Sparkles className="w-4 h-4 text-purple-400 animate-spin" />
            <span>Aggregating transaction logs & querying AI Engine...</span>
          </div>
          <p className="text-xs text-slate-400">Evaluating category weights, credit card ratios, and savings recommendations</p>
        </div>
      )}

      {/* REPORT DISPLAY */}
      {insights && !loading && (
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          className="space-y-6"
        >
          {/* Executive Summary & Health Score */}
          <div className="bg-slate-900/90 border border-slate-800 p-6 rounded-2xl flex flex-col md:flex-row items-start justify-between gap-6">
            <div className="space-y-2 flex-1">
              <Badge variant="indigo" size="sm">
                Generated by {insights.generatedBy || 'Gemini AI'}
              </Badge>
              <p className="text-sm text-slate-200 leading-relaxed">
                {insights.summary}
              </p>
            </div>

            {insights.healthScore !== undefined && (
              <div className="bg-slate-950 p-4 rounded-xl border border-slate-800 text-center min-w-[140px] shrink-0">
                <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Health Rating</span>
                <div className={`text-3xl font-black font-heading mt-1 ${insights.healthScore >= 75 ? 'text-emerald-400' : insights.healthScore >= 50 ? 'text-amber-400' : 'text-rose-400'}`}>
                  {insights.healthScore}<span className="text-xs text-slate-500 font-normal">/100</span>
                </div>
              </div>
            )}
          </div>

          {/* Grid of Patterns, Anomalies & Suggestions */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            
            {/* Patterns */}
            <div className="bg-slate-900/60 p-5 rounded-2xl border border-indigo-500/20 space-y-4">
              <div className="flex items-center gap-2 font-bold text-sm text-indigo-300">
                <TrendingDown className="w-4 h-4" />
                <span>Observed Patterns</span>
              </div>
              <div className="space-y-3 text-xs">
                {insights.patterns?.map((item, idx) => (
                  <div key={idx} className="bg-slate-950 p-3 rounded-xl border border-slate-800/80 border-l-2 border-l-indigo-500 space-y-1">
                    <div className="flex justify-between items-center font-bold text-slate-200">
                      <span>{item.title}</span>
                      <Badge variant={item.impact === 'High' ? 'rose' : item.impact === 'Medium' ? 'amber' : 'indigo'} size="sm">
                        {item.impact || 'Info'}
                      </Badge>
                    </div>
                    <p className="text-slate-400">{item.description}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Anomalies */}
            <div className="bg-slate-900/60 p-5 rounded-2xl border border-rose-500/20 space-y-4">
              <div className="flex items-center gap-2 font-bold text-sm text-rose-300">
                <AlertTriangle className="w-4 h-4" />
                <span>High Outliers & Spikes</span>
              </div>
              <div className="space-y-3 text-xs">
                {insights.anomalies?.map((item, idx) => (
                  <div key={idx} className="bg-slate-950 p-3 rounded-xl border border-slate-800/80 border-l-2 border-l-rose-500 space-y-1">
                    <span className="font-bold text-slate-200 block">{item.title}</span>
                    <p className="text-slate-400">{item.description}</p>
                  </div>
                ))}
              </div>
            </div>

            {/* Savings Tips */}
            <div className="bg-slate-900/60 p-5 rounded-2xl border border-emerald-500/20 space-y-4">
              <div className="flex items-center gap-2 font-bold text-sm text-emerald-300">
                <Lightbulb className="w-4 h-4" />
                <span>Savings Opportunities</span>
              </div>
              <div className="space-y-3 text-xs">
                {insights.suggestions?.map((item, idx) => (
                  <div key={idx} className="bg-slate-950 p-3 rounded-xl border border-slate-800/80 border-l-2 border-l-emerald-500 space-y-1">
                    <div className="flex justify-between items-center font-bold text-slate-200">
                      <span>{item.title}</span>
                      {item.potentialSavings && (
                        <Badge variant="emerald" size="sm">
                          {item.potentialSavings}
                        </Badge>
                      )}
                    </div>
                    <p className="text-slate-400">{item.description}</p>
                  </div>
                ))}
              </div>
            </div>

          </div>
        </motion.div>
      )}

    </Card>
  );
}
